#!/bin/zsh
# One-command Homebrew tap publish:
#   ./scripts/publish-tap.sh 0.2.0
#
# What it does, in order:
#   1. Builds release artifacts (release.sh): CLI tarball + S1.app zip.
#   2. Uploads them to GitHub Release v<version> (creates it if missing).
#   3. Clones the tap repo, writes Formula/s1.rb + Casks/s1.rb with the
#      real version + sha256s, commits and pushes.
#
# Prerequisites (one-time):
#   - git tag pushed:   git tag v0.2.0 && git push origin v0.2.0
#   - tap repo exists:  github.com/Matthew-Eucaristo/homebrew-tap (empty README is fine)
#   - `gh auth login`   (for the release upload; falls back to manual instructions)
#
# Override the tap location:  TAP_REPO=you/homebrew-tap ./scripts/publish-tap.sh 0.2.0
set -euo pipefail
VERSION="${1:?usage: ./scripts/publish-tap.sh <version>  e.g. 0.2.0}"
cd "$(dirname "$0")/.."
REPO="Matthew-Eucaristo/s1"
TAP_REPO="${TAP_REPO:-Matthew-Eucaristo/homebrew-tap}"
TAG="v${VERSION}"

TAR="s1-${VERSION}-macos.tar.gz"
ZIP="S1-${VERSION}-app.zip"

# -- 1. artifacts -------------------------------------------------------------
[[ -f $TAR && -f $ZIP ]] || ./scripts/release.sh "$VERSION"
TAR_SHA=$(shasum -a 256 "$TAR" | awk '{print $1}')
ZIP_SHA=$(shasum -a 256 "$ZIP" | awk '{print $1}')
echo "tarball sha256: $TAR_SHA"
echo "app zip sha256: $ZIP_SHA"

# -- 2. GitHub Release ---------------------------------------------------------
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
        gh release upload "$TAG" "$TAR" "$ZIP" --repo "$REPO" --clobber
        echo "uploaded to existing release $TAG"
    else
        gh release create "$TAG" "$TAR" "$ZIP" --repo "$REPO" \
            --title "s1 $VERSION" --generate-notes
        echo "created release $TAG"
    fi
else
    echo "!! gh not authenticated — upload these to the GitHub Release manually:"
    echo "   https://github.com/$REPO/releases/new?tag=$TAG"
    echo "   files: $TAR, $ZIP"
    echo "   (the tap files below are still generated — publish them after upload)"
fi

# -- 3. tap repo ---------------------------------------------------------------
TAP_DIR=$(mktemp -d)/tap
git clone "https://github.com/$TAP_REPO" "$TAP_DIR"
mkdir -p "$TAP_DIR/Formula" "$TAP_DIR/Casks"

cat > "$TAP_DIR/Formula/s1.rb" <<EOF
# Generated by s1's scripts/publish-tap.sh — regenerate, don't hand-edit.
class S1 < Formula
  desc "Voice-first agent — fast System 1 + LLM System 2, accessibility-driven"
  homepage "https://github.com/$REPO"
  url "https://github.com/$REPO/releases/download/$TAG/s1-$VERSION-macos.tar.gz"
  sha256 "$TAR_SHA"
  license "MIT"

  depends_on macos: :sequoia

  def install
    bin.install "s1"
  end

  def caveats
    <<~EOS
      s1 drives your Mac via Accessibility, Screen Recording, and Speech —
      macOS prompts your terminal app on first use; \`s1 preflight\` lists
      what's still missing.
      Menu-bar companion:  brew install --cask s1
      Local model brain:   brew install ollama && ollama pull gemma3:4b
    EOS
  end

  test do
    assert_match "OVERVIEW", shell_output("#{bin}/s1 --help")
  end
end
EOF

cat > "$TAP_DIR/Casks/s1.rb" <<EOF
# Generated by s1's scripts/publish-tap.sh — regenerate, don't hand-edit.
cask "s1" do
  version "$VERSION"
  sha256 "$ZIP_SHA"

  url "https://github.com/$REPO/releases/download/$TAG/S1-#{version}-app.zip"
  name "S1"
  desc "Voice-first agent — menu-bar companion (System 1 + System 2)"
  homepage "https://github.com/$REPO"

  depends_on macos: :sequoia

  app "S1.app"
  uninstall quit: "com.matthew.s1.app"

  zap trash: [
    "~/.s1",
    "~/Library/Application Scripts/com.matthew.s1.app",
    "~/Library/Containers/com.matthew.s1.app",
    "~/Library/HTTPStorages/com.matthew.s1.app",
    "~/Library/Preferences/com.matthew.s1.app.plist",
    "~/Library/Saved Application State/com.matthew.s1.app.savedState",
  ]

  caveats <<~EOS
    First launch asks for Accessibility, Screen Recording, and (for voice)
    Microphone — System Settings prompts; \`s1 preflight\` lists any gaps.
    Builds ship self-signed (not notarized): if Gatekeeper blocks the first
    launch, \`brew reinstall --cask s1 --no-quarantine\` or
    \`xattr -dr com.apple.quarantine /Applications/S1.app\`.
  EOS
end
EOF

cd "$TAP_DIR"
git add Formula/s1.rb Casks/s1.rb
if git diff --cached --quiet; then
    echo "tap already at $VERSION — nothing to publish"
else
    git commit -m "s1 $VERSION"
    git push
    echo "published $TAP_REPO @ $VERSION"
fi

cat <<MSG

Done. Users install with:
  brew tap ${TAP_REPO/homebrew-/}
  brew install s1             # CLI
  brew install --cask s1      # menu-bar app

Clean removal:
  brew uninstall --formula s1
  brew uninstall --cask s1            # quits + removes /Applications/S1.app
  brew uninstall --cask s1 --zap      # + wipes ~/.s1 and Library traces
MSG
