#!/bin/zsh
# One-command Homebrew tap publish:
#   ./scripts/publish-tap.sh 0.2.0
#
# What it does, in order:
#   1. Builds the release artifact (scripts/make-app.sh): S1.app zip —
#      the bundle carries BOTH the GUI (Contents/MacOS/S1) and the CLI
#      (Contents/Resources/s1) that the cask links onto PATH.
#   2. Uploads the zip to GitHub Release v<version> (creates it if missing);
#      without `gh` auth it rides inside the tap repo under releases/.
#   3. Clones the tap repo, writes Casks/s1.rb with the real version +
#      sha256, commits and pushes.
#
# Prerequisites (one-time):
#   - git tag pushed:   git tag v0.2.0 && git push origin v0.2.0
#   - tap repo exists:  github.com/Matthew-Eucaristo/homebrew-tap
#
# Override the tap location:  TAP_REPO=you/homebrew-tap ./scripts/publish-tap.sh 0.2.0
set -euo pipefail
VERSION="${1:?usage: ./scripts/publish-tap.sh <version>  e.g. 0.2.0}"
cd "$(dirname "$0")/.."
REPO="Matthew-Eucaristo/s1"
TAP_REPO="${TAP_REPO:-Matthew-Eucaristo/homebrew-tap}"
TAG="v${VERSION}"

ZIP="S1-${VERSION}-app.zip"

# -- 1. artifact ---------------------------------------------------------------
[[ -f "dist/$ZIP" ]] || ./scripts/make-app.sh release
ZIP_SHA=$(shasum -a 256 "dist/$ZIP" | awk '{print $1}')
echo "app zip sha256: $ZIP_SHA"

# -- 2. artifact hosting --------------------------------------------------------
RELEASE_URLS=0
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    RELEASE_URLS=1
    if gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1; then
        gh release upload "$TAG" "dist/$ZIP" --repo "$REPO" --clobber
        echo "uploaded to existing release $TAG"
    else
        gh release create "$TAG" "dist/$ZIP" --repo "$REPO" \
            --title "s1 $VERSION" --generate-notes
        echo "created release $TAG"
    fi
else
    echo "!! gh not authenticated — artifact goes into the tap repo instead"
fi

# -- 3. tap repo ---------------------------------------------------------------
TAP_DIR=$(mktemp -d)/tap
git clone "https://github.com/$TAP_REPO" "$TAP_DIR"
mkdir -p "$TAP_DIR/Casks" "$TAP_DIR/releases/$TAG"

if [[ $RELEASE_URLS == 1 ]]; then
    ZIP_URL="https://github.com/$REPO/releases/download/$TAG/S1-#{version}-app.zip"
else
    cp "dist/$ZIP" "$TAP_DIR/releases/$TAG/"
    # Commit the artifact FIRST so the cask URL can pin to the commit sha —
    # raw.githubusercontent.com/.../main/... edge-caches large files and
    # keeps serving the previous zip long after push.
    cd "$TAP_DIR"
    git add "releases/$TAG"
    git diff --cached --quiet || git commit -m "s1 $VERSION artifact"
    ART_SHA=$(git rev-parse HEAD)
    cd - >/dev/null
    ZIP_URL="https://raw.githubusercontent.com/$TAP_REPO/$ART_SHA/releases/$TAG/S1-#{version}-app.zip"
fi

cat > "$TAP_DIR/Casks/s1.rb" <<EOF
# Generated by s1's scripts/publish-tap.sh — regenerate, don't hand-edit.
cask "s1" do
  version "$VERSION"
  sha256 "$ZIP_SHA"

  url "$ZIP_URL"
  name "s1"
  desc "Voice-first agent — menu-bar companion (System 1 + System 2), CLI included"
  homepage "https://github.com/$REPO"

  depends_on macos: :tahoe

  app "S1.app"
  # The CLI ships inside the bundle (Contents/Resources/s1) — brew links it
  # into HOMEBREW_PREFIX/bin so \`s1\` works on PATH from the same install.
  binary "#{appdir}/S1.app/Contents/Resources/s1"
  uninstall launchctl: ["com.matthew.s1.serve", "sh.brew.s1"],
            quit:      ["com.mattheweuc.s1", "com.matthew.s1.app"]

  zap trash: [
    "~/.s1",
    "~/Library/Application Scripts/com.mattheweuc.s1",
    "~/Library/Application Scripts/com.matthew.s1.app",
    "~/Library/Containers/com.mattheweuc.s1",
    "~/Library/Containers/com.matthew.s1.app",
    "~/Library/HTTPStorages/com.mattheweuc.s1",
    "~/Library/HTTPStorages/com.matthew.s1.app",
    "~/Library/LaunchAgents/com.matthew.s1.serve.plist",
    "~/Library/LaunchAgents/sh.brew.s1.plist",
    "~/Library/Preferences/com.mattheweuc.s1.plist",
    "~/Library/Preferences/com.matthew.s1.app.plist",
    "~/Library/Saved Application State/com.mattheweuc.s1.savedState",
    "~/Library/Saved Application State/com.matthew.s1.app.savedState",
  ]

  caveats <<~EOS
    Ad-hoc signed → Gatekeeper will block the first open. Either install
    with \`brew install --cask --no-quarantine s1\`, or once:
      xattr -dr com.apple.quarantine /Applications/S1.app
    Then open S1 and grant Accessibility + Screen Recording + Microphone
    when it asks — \`s1 preflight\` shows the score.

      Always-on listener:        s1 serve --install   (launchd agent, armed at login)
      Local model brain:         brew install ollama && ollama pull gemma3:4b
      Full reset:                brew uninstall --cask s1 --zap
  EOS
end
EOF

cd "$TAP_DIR"
git add Casks/s1.rb
if git diff --cached --quiet; then
    echo "tap already at $VERSION — nothing to publish"
else
    git commit -m "s1 $VERSION"
    git push
    echo "published $TAP_REPO @ $VERSION"
fi

cat <<MSG

Done. Users install with:
  brew tap ${TAP_REPO/homebrew-/}
  brew install --cask s1      # GUI + \`s1\` CLI (linked from inside the app)

Clean removal:
  brew uninstall --cask s1            # quits + removes /Applications/S1.app
  brew uninstall --cask s1 --zap      # + wipes ~/.s1 and Library traces
MSG
